### ISSUE TITLE
Verbose option?

### ISSUE THREAD

**Issue by rickmanelius** [andrewmarmion/bitrise-step-firebase-dsym-upload#5]
Since we have two Firebase endpoints (staging vs production), is there any chance we can expose other values about which place it was successfully sent to? Perhaps a verbose = true option?

**Comment by andrewmarmion** [comment]
The way the step works is that is uses Google's own uploader. It uses the information from the GoogleService-Info.plist to route the dSYMs to the correct location. That's why you have to pass the location of your GoogleService-Info.plist, along with that of Fabric and your dSYMs. 

As you can see from their [documentation](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports) there are not many options to pass. 

Even following their option to get additional instructions doesn't produce much.  

> Note: If you're having trouble, run upload-symbols without any parameters to get usage notes and additional instructions.

The above yields the following result:

    error: No API Key or Google Services file provided

Without parsing the GoogleService-Info.plist (which I think is beyond the scope of this step), I am not sure what other information I could add to the output (other than the locations which you have passed to the step).

**Comment by andrewmarmion** [comment]
Closing this as it is not possible to implement.

**Comment by rickmanelius** [comment]
Thanks, @andrewmarmion! It turns out I figured out what the issue was and I documented it here https://discuss.bitrise.io/t/download-dsyms-from-app-store-connect-for-testflight-apps-using-bitcode/12565/2. This step wasn't working because the xcode-archive step has default options to enable bitcode, which when disabled allows this step to work.
